name: development
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.3'

    - name: test
      run: go test ./...

    - name: deploy
      run: |
        mkdir -p $HOME/.ssh
        echo ${{secrets.LINODE_PRIVATE_KEY}} >> $HOME/.ssh/id_rsa
        scp README.md tidio.preferit.se:
