name: development
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.3'

    - name: build
      run: |
          mkdir -p /tmp/tidio
          go build -o /tmp/tidio/tidio ./cmd/tidio
          cp -r ./etc /tmp/tidio
          cp install.sh /tmp/tidio

    - name: test
      run: |
          go get github.com/gregoryv/uncover/...
          go test -coverprofile /tmp/c.out ./...
          $GOPATH/bin/uncover -min 80 /tmp/c.out

    - name: deploy
      env:
        LINODE_PRIVATE_KEY: ${{secrets.LINODE_PRIVATE_KEY}}
      run: |
        mkdir -p $HOME/.ssh
        go run ./internal/cmd/setupGithubSSH/
        rsync -av /tmp/tidio/ ${{secrets.LINODE_USER}}@tidio.preferit.se:tidio/
        ssh ${{secrets.LINODE_USER}}@tidio.preferit.se 'cd tidio; sudo ./install.sh'
