name: development
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.3'

    - name: test
      run: go test ./...

    - name: deploy
      env:
        LINODE_PRIVATE_KEY: ${{secrets.LINODE_PRIVATE_KEY}}
      run: |
        mkdir -p $HOME/.ssh
        go run ./internal/cmd/setupGithubSSH/
        ls -al $HOME/.ssh
        cat $HOME/.ssh/known_hosts
        scp -v README.md tidio.preferit.se:
