name: development
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-go@v1
      with:
        go-version: '1.17'

    - name: build
      env:
        GOPATH: "/tmp"
        PATH: "/bin:/usr/bin:/tmp/bin"
      run: |
          ./ci.sh setup build

    - name: test
      env:
        GOPATH: "/tmp"
      run: |
          ./ci.sh test

    - name: deploy
      env:
        LINODE_PRIVATE_KEY: ${{secrets.LINODE_PRIVATE_KEY}}
        LINODE_USER: ${{secrets.LINODE_USER}}
        TIDIO_HOST: tidio.preferit.se
      run: |
        ./ci.sh deploy
